name: Build & Publish Gradle Project

on:
  push:

jobs:
  build-gradle-project:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Kotlin
      uses: fwilhe2/setup-kotlin@main
      with:
        kotlin-version: '1.7.20'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    #- name: Build Gradle
    #  run: ./gradlew build --refresh-dependencies
    - name: Read packages.txt file
      run: |
        echo "PACKAGE_LIST=$(cat packages.txt)" >> $GITHUB_ENV
    - name: Delete Existing Package
      if: success()
      run: |
        for PACKAGE in $PACKAGE_LIST; do
          PACKAGE_NAME="$(echo $PACKAGE | cut -d':' -f1)"
          PACKAGE_VERSION="$(echo $PACKAGE | cut -d':' -f2)"
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://maven.pkg.github.com/eugeis/ee/${PACKAGE_NAME}/${PACKAGE_VERSION}"
        done
    - name: Publish Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew publish
